name: "Build Zenoh Recipes"
description: "Build steps for Zenoh recipes using kas"

runs:
  using: composite
  steps:
    - name: Install kas
      id: kas
      shell: bash
      run: |
        wget https://github.com/siemens/kas/raw/4.8.1/kas-container -O /tmp/kas
        chmod +x /tmp/kas
        echo "KAS=/tmp/kas" >> "${GITHUB_OUTPUT}"

    - name: Select kas config
      id: config
      shell: bash
      run: |
        echo "KAS_CONFIG=kas/zenoh-cpp.yml" >> "${GITHUB_OUTPUT}"

    - name: Build with kas
      shell: bash
      run: |
        ${{ steps.kas.outputs.KAS }} build ${{ steps.config.outputs.KAS_CONFIG }}

    - name: List built RPMs and native components
      shell: bash
      run: |
        find build/tmp/deploy/rpm/x86_64_v3 \
          -name '*zenoh*.rpm' \
          -exec echo -e "\n=== {} ===" \; \
          -exec rpm -qp --queryformat "[%-20{=NAME} %{FILENAMES}\n]" {} \;

        find build/tmp/sysroots-components/x86_64 \
          -depth -maxdepth 1 \
          -name 'zenoh*-native' \
          -exec echo -e "\n=== {} ===" \; \
          -exec tree -I sysroot-providers {} \;
