name: Zenoh Yocto Build

on:
  push:
    paths-ignore:
      - README
  pull_request:
    branches:
      - master
    paths-ignore:
      - README

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build Zenoh recipes
        uses: ./.github/actions/kas-build

